<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIFKaDxv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIFKaDxv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIFKaDxv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIFKaDxv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIFKaDxv\App_KernelDevDebugContainer([
    'container.build_hash' => 'IFKaDxv',
    'container.build_id' => '8dc82ff6',
    'container.build_time' => 1677166018,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIFKaDxv');
